### ISSUE TITLE
Filter maven properties

### ISSUE THREAD

**Issue by llorllale** [llorllale/loggit-maven-plugin#96]
Allow filtering of maven properties as suggested in #93, so that for example the occurrence of `${project.artifactId}` would be replaced by the project's artifactId.

**Comment by llorllale** [comment]
@Sami32 what do you think of just using the [`maven-resources-plugin`](https://maven.apache.org/plugins/maven-resources-plugin) for this?

**Comment by Sami32** [comment]
Hum...
We only use the default Maven one, as the new maven-resources-plugin requires Surefire 0.21 that need Maven 3.5.x AFAIK.
So we don't want lose compatibility with Maven version 3.2.5 or at least 3.3.3 because many Linux distributions have only these in their repositories for now.

So i'm afraid about the overall plugin compatibility, but as this feature come to my mind after having looked at releases and compared many similar changelog plugins, it is not an absolute need feature for our project so as long as your plugin compatibility is not affected i will be fine with your choice.

I hope that my novice comment do make some sens to you.

**Comment by Sami32** [comment]
I just discovered an other use case for the Linux packages:
https://www.debian.org/doc/manuals/maint-guide/dreq.en.html#changelog

**Comment by Sami32** [comment]
It seeem that the latest Surefire version 2.22.0 fixed their regression since 2.20.1 , so now if you still want use `maven-resources-plugin` it should be fine ;)

**Comment by Sami32** [comment]
I should have added that now the latest Surefire support older Maven version than 3.5.0 but not anymore Java 7 as it requires JUnit5 that dropped the Java 7 support AFAIK.

**Comment by Sami32** [comment]
It seem i was wrong Surefire 2.22 still support older JUnit versions so it should be fine.
Sorry for the noise :/

**Comment by llorllale** [comment]
@Sami32 I'm a bit confused: is this issue still valid then or no?

**Comment by Sami32** [comment]
Sorry i was not clear :(
I was just trying to update my answer to your question as best i can.

Since the latest Surefire 2.22, you can now use `maven-resources-plugin` if you still want to. I mean without any known drawback effect AFAIK.

**Comment by llorllale** [comment]
@Sami32 ok, I'm closing this then
